[tools]
rojo = { source = "rojo-rbx/rojo", version = "7.0.0" }
wally = { source = "UpliftGames/wally", version = "0.3.1" }
luau-analyze = { source = "JohnnyMorganz/luau-analyze-rojo", version = "0.525.2" }