[package]
name = "corecii/roact-template"
version = "0.1.0"
description = "A runtime instance-to-Roact translator"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*"]
include = ["wally.toml", "src", "src/lib", "src/lib/**", "default.project.json", "README.md",
	"LICENSE", "moonwave.toml", "foreman.toml", "selene.toml", ".editorconfig"]

[dependencies]
ApiDumpStatic = "corecii/api-dump-static@^1.0"