name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v2

      - name: Install Foreman
        uses: Roblox/setup-foreman@v1
        with:
          version: "^1.0.0"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Packages
        run: wally install

      - name: Build Packaged Library
        run: rojo build -o packaged.rbxm packaged.project.json
        
      - name: Archive Packaged Library
        uses: actions/upload-artifact@v2
        with:
          name: Library (packaged with dependencies)
          path: packaged.rbxm