name: Release

on:
  release:
    types: [created]

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Check out Repository
        uses: actions/checkout@v2

      - name: Install Foreman
        uses: Roblox/setup-foreman@v1
        with:
          version: "^1.0.0"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Packages
        run: wally install

      - name: Build Packaged Library
        run: rojo build -o packaged.rbxm packaged.project.json
        
      - name: Archive Packaged Library
        uses: actions/upload-artifact@v2
        with:
          name: Library (packaged with dependencies)
          path: packaged.rbxm

  publish:
    name: Upload release artifacts
    runs-on: ubuntu-latest
    needs: ['windows']
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2

      - name: List directory and files
        run: |
          pwd
          ls -l
      
      - name: Get tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: List tag and files
        run: |
          echo ${{ env.TAG }}
          ls -l
      
      - name: Upload release artifacts
        run: gh release upload ${{ env.TAG }} packaged.rbxm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
