name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repository
        uses: actions/checkout@v2

      - name: Install Foreman
        uses: Roblox/setup-foreman@v1
        with:
          version: "^1.0.0"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Packages (Manually)
        run: |
          # We do it this way so that it's easier for non-wally users to update the static API dump
          mkdir Packages;
          git clone --depth 1 --branch latest-v1 --single-branch https://github.com/Corecii/api-dump-static  ./Packages/ApiDumpStatic
          cd 

      - name: Build Packaged Library
        run: rojo build -o RoactTemplate.rbxm rojo-packaged.project.json
        
      - name: Archive Packaged Library
        uses: actions/upload-artifact@v2
        with:
          name: RoactTemplatePackaged
          path: RoactTemplate.rbxm

  publish:
    name: Upload release artifacts
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2

      - name: List directory and files
        run: |
          pwd
          ls -l
      
      - name: Get tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: List tag and files
        run: |
          echo ${{ env.TAG }}
          ls -l
      
      - name: Upload release artifacts
        run: gh release upload ${{ env.TAG }} RoactTemplatePackaged/RoactTemplate.rbxm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
